library("DESeq2")
cts <- read.table("D425_Day30_vs_HLX2_7_KO_Day30.count.csv", header = TRUE, row.names = 1)
cts <- as.matrix(cts)
coldata <- read.table("D425_Day30_vs_HLX2_7_KO_Day30.design.csv", header = TRUE, row.names = 1)
dds <- DESeqDataSetFromMatrix(countData = cts, colData = coldata, design = ~ condition)
dds <- DESeq(dds)
res <- results(dds)
write.table(as.data.frame(res), sep="\t", file="D425_Day30_vs_HLX2_7_KO_Day30.DE.csv")
plotMA(res, ylim=c(-2,2))
q()
